apiVersion: v1
kind: Service
metadata:
  name: employee-ui-svc
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    app: employee-ui-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-ui-pod
  template:
    metadata:
      labels:
        app: employee-ui-pod
    spec:
      containers:
        - name: employee-ui
          image: bmsvega2k/springbootreactjs:envsh0.4
          ports:
            - containerPort: 80
          env:
            - name: VITE_APIURL
              value: "http://34.41.14.100:8080/api"
